title: Ruang Belajar - Materi Pelengkap
description: Repositori berbagai materi pelengkap perkuliahan
domain: pujangga123.github.io
url: http://ruang-belajar.github.io/materi-pelengkap
github_username:  pujangga123

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme